; -------------------------------------------------------
; Generated by ricc — Rust-Inspired Compiler
; Source file : /tmp/test_loop.ric
; Target      : Linux x86-64 (System V ABI)
; Assembler   : NASM (nasm -f elf64)
; -------------------------------------------------------

default rel
section .text

global sum_to
sum_to:
    push rbp
    mov rbp, rsp
    sub rsp, 104
    mov qword [rbp -8], rdi
.sum_to_entry_0:
    mov rax, qword [rbp -8]
    mov qword [rbp -32], rax
    mov rax, 0
    mov qword [rbp -16], rax
    mov rax, 1
    mov qword [rbp -24], rax
    jmp .sum_to_while_header_1
.sum_to_while_header_1:
    mov rax, qword [rbp -24]
    mov qword [rbp -40], rax
    mov rax, qword [rbp -8]
    mov qword [rbp -48], rax
    mov rax, qword [rbp -40]
    mov rcx, qword [rbp -48]
    cmp rax, rcx
    setle al
    movzx rax, al
    mov qword [rbp -56], rax
    mov rax, qword [rbp -56]
    test rax, rax
    jnz .sum_to_while_body_2
    jmp .sum_to_while_exit_3
.sum_to_while_body_2:
    mov rax, qword [rbp -16]
    mov qword [rbp -64], rax
    mov rax, qword [rbp -24]
    mov qword [rbp -72], rax
    mov rax, qword [rbp -64]
    mov rcx, qword [rbp -72]
    add rax, rcx
    mov qword [rbp -80], rax
    mov rax, qword [rbp -80]
    mov qword [rbp -16], rax
    mov rax, qword [rbp -24]
    mov qword [rbp -88], rax
    mov rax, qword [rbp -88]
    mov rcx, 1
    add rax, rcx
    mov qword [rbp -96], rax
    mov rax, qword [rbp -96]
    mov qword [rbp -24], rax
    jmp .sum_to_while_header_1
.sum_to_while_exit_3:
    mov rax, qword [rbp -16]
    mov qword [rbp -104], rax
    mov rax, qword [rbp -104]
    leave
    ret

global main
main:
    push rbp
    mov rbp, rsp
    sub rsp, 8
.main_entry_0:
    mov rdi, 15
    call sum_to
    mov qword [rbp -8], rax
    mov rax, qword [rbp -8]
    leave
    ret

